SELECT
  AU.AUTHOR_ID,
  AU.AUTHOR_NAME,
  B.CATEGORY,
  SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
FROM BOOK_SALES BS
JOIN BOOK B       ON BS.BOOK_ID = B.BOOK_ID
JOIN AUTHOR AU    ON B.AUTHOR_ID = AU.AUTHOR_ID
WHERE BS.SALES_DATE >= '2022-01-01'
  AND BS.SALES_DATE <  '2022-02-01'
GROUP BY
  AU.AUTHOR_ID, AU.AUTHOR_NAME, B.CATEGORY
ORDER BY
  AU.AUTHOR_ID ASC,
  B.CATEGORY DESC;