-- 코드를 작성해주세요
SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO AS A
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LEN
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    ) M
ON A.FISH_TYPE = M.FISH_TYPE
AND A.LENGTH = M.MAX_LEN
JOIN FISH_NAME_INFO B
ON A.FISH_TYPE = B.FISH_TYPE
ORDER BY A.ID;