-- 코드를 작성해주세요
SELECT SUM(H2.SCORE) AS SCORE, H1.EMP_NO, H1.EMP_NAME, H1.POSITION, H1.EMAIL
FROM HR_EMPLOYEES AS H1
JOIN HR_GRADE AS H2 
ON H1.EMP_NO = H2.EMP_NO
GROUP BY H1.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;
