-- 코드를 입력하세요
SELECT ICE.INGREDIENT_TYPE, SUM(FI.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF AS FI
JOIN ICECREAM_INFO AS ICE
ON FI.FLAVOR = ICE.FLAVOR
GROUP BY ICE.INGREDIENT_TYPE
ORDER BY FI.TOTAL_ORDER ASC;